apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: socialdev.io
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./k8s/*.yaml
build:
  # insecureRegistries:
  #   - pi.eryx.local:5000/
  local:
    push: true
  artifacts:
    - image: ghcr.io/omer-bar/socialdev.io/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: ghcr.io/omer-bar/socialdev.io/profiles
      context: profiles
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: ghcr.io/omer-bar/socialdev.io/posts
      context: posts
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: ghcr.io/omer-bar/socialdev.io/comments
      context: comments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: ghcr.io/omer-bar/socialdev.io/friends
      context: friends
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: ghcr.io/omer-bar/socialdev.io/client
      context: client
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.css
            dest: .
          - src: src/**/*.jpg
            dest: .
      docker:
        dockerfile: Dockerfile
# test:
#   - image: ghcr.io/omer-bar/socialdev.io/auth
#     context: auth
#     custom:
#       - command: npm run test
#         timeoutSeconds: 10

# deploy:
#   kubectl: {}
#     hooks:
#       before:
#         - host:
#             command: ["sh", "-c", "npm run test"]
#             os: [darwin, linux]
#             dir: ./auth
