.common_config: &common
  sync:
    manual:
      - src: src/**/*.ts
        dest: .

apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: socialdev.io
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./k8s/*.yaml
build:
  tagPolicy:
    sha256: {}
  # insecureRegistries:
  #   - pi.eryx.local:5000/
  local:
    push: true
  artifacts:
    - image: ghcr.io/omer-bar/socialdev.io/auth
      context: auth
      <<: *common

    - image: ghcr.io/omer-bar/socialdev.io/profiles
      context: profiles
      <<: *common

    - image: ghcr.io/omer-bar/socialdev.io/posts
      context: posts
      <<: *common

    - image: ghcr.io/omer-bar/socialdev.io/comments
      context: comments
      <<: *common

    - image: ghcr.io/omer-bar/socialdev.io/friends
      context: friends
      <<: *common

    - image: ghcr.io/omer-bar/socialdev.io/client
      context: client
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.css
            dest: .
          - src: src/**/*.jpg
            dest: .
      docker:
        dockerfile: Dockerfile
