apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: ghcr.io/eryx666/socialdev.io/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/eryx666/socialdev.io/profiles
      context: profiles
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/eryx666/socialdev.io/posts
      context: posts
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/eryx666/socialdev.io/comments
      context: comments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/eryx666/socialdev.io/friends
      context: friends
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
<<<<<<< HEAD
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/eryx666/socialdev.io/client
      context: client
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.css
            dest: .
          - src: src/**/*.jpg
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
# test:
#   - image: ghcr.io/eryx666/socialdev.io/auth
#     context: auth
#     custom:
#       - command: npm run test
#         timeoutSeconds: 10

deploy:
  kubectl: {}
#     hooks:
#       before:
#         - host:
#             command: ["sh", "-c", "npm run test"]
#             os: [darwin, linux]
#             dir: ./auth
=======
    - image: pi.eryx.local:5000/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
>>>>>>> main
