apiVersion: skaffold/v2beta10
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  insecureRegistries:
    - pi.eryx.local:5000/
  local:
    push: false
  artifacts:
    - image: ghcr.io/eryx666/socialdev.io/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ghcr.io/eryx666/socialdev.io/profiles
      context: profiles
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ghcr.io/eryx666/socialdev.io/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ghcr.io/eryx666/socialdev.io/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ghcr.io/eryx666/socialdev.io/friends
      context: friends
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
