apiVersion: skaffold/v2beta10
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  insecureRegistries:
    - pi.eryx.local:5000/
  local:
    push: true
  artifacts:
    - image: pi.eryx.local:5000/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pi.eryx.local:5000/profiles
      context: profiles
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pi.eryx.local:5000/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pi.eryx.local:5000/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pi.eryx.local:5000/friends
      context: friends
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pi.eryx.local:5000/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
