apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-new-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-new
  template:
    metadata:
      labels:
        app: client-new
    spec:
      containers:
        - name: client-new
          image: pi.eryx.local:5000/client-new
---
apiVersion: v1
kind: Service
metadata:
  name: client-new-srv
spec:
  selector:
    app: client-new
  ports:
    - name: client-new
      protocol: TCP
      port: 3000
      targetPort: 3000
