apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-depl
  namespace: socialdev
  labels:
    app.kubernetes.io/name: profiles-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiles
  template:
    metadata:
      labels:
        app: profiles
    spec:
      containers:
        - name: profiles
          image: ghcr.io/omer-bar/socialdev.io/profiles
          imagePullPolicy: Always
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: socialdev
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: profiles-srv
  namespace: socialdev
  labels:
    app.kubernetes.io/name: profiles-srv
spec:
  selector:
    app: profiles
  ports:
    - name: profiles
      protocol: TCP
      port: 3000
      targetPort: 3000
