apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friends
  template:
    metadata:
      labels:
        app: friends
    spec:
      containers:
        - name: friends
          image: pi.eryx.local:5000/friends
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: socialnet
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: friends-srv
spec:
  selector:
    app: friends
  ports:
    - name: friends
      protocol: TCP
      port: 3000
      targetPort: 3000
